### ISSUE TITLE
package fails installing on Windows

### ISSUE THREAD

**Issue by reisingerf** [clintval/sample-sheet#90]
I tried to install the package on a Windows machine with `pip install sample_sheet` following the docs. Unfortunately it resulted in an error that looks like a Linux/Windows path compatibility issue:

```
Traceback (most recent call last):
     File "<string>", line 1, in <module>
     File "C:\Users\Foo\AppData\Local\Temp\pip-install-a02d2846\sample-sheet\setup.py", line 28, in <module>
       packages=setuptools.find_packages(where='./'),
     File "c:\users\tpham1.unimelb\appdata\local\programs\python\python37\lib\site-packages\setuptools\__init__.py", line 71, in find
       convert_path(where),
     File "c:\users\tpham1.unimelb\appdata\local\programs\python\python37\lib\distutils\util.py", line 112, in convert_path
       raise ValueError("path '%s' cannot end with '/'" % pathname)
   ValueError: path './' cannot end with '/'

   ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\TPHAM1~1.UNI\AppData\Local\Temp\pip-install-a02d2846\sample-sheet\
```

**Comment by clintval** [comment]
Hey @reisingerf!

Thanks for posting. TravisCI doesn't have an easy way for me to use automated testing on Windows platforms so I am flying blind.

I just patched this one bug in `setup.py` but there may be others related to Windows incompatibility. Please keep me posted!

I just published [`0.9.4`](https://pypi.org/project/sample-sheet/0.9.4/) so consider reinstalling. If you are looking for a Bioconda update, that should come later in the week.
